{
    "token": 'NgifG6gVrt09L5N8UYzmmDGNP78w4GPBMb_NdxOx9K8JKcjUGg2dTgoviUNVO6lDPTe480xm2dZkY_HRhaHeKiNqIbYhZD8z8UrTHeGlRIXh65h1ZDteOauK',
    "study_id": '699819dea9b3dfc5842e749d',
    "max_concurrent_sessions": 10,
    "workload_checker_period": 60
}